repos:
  - repo: local
    hooks:
      - id: ruff-format
        name: ruff (format)
        entry: ruff format
        language: system
        types: [python]
        args: ["--line-length", "120"]

      - id: ruff
        name: ruff (fix)
        entry: ruff
        language: system
        types: [python]
        args: ["check", "--fix"]
