repos:
  - repo: local
    hooks:
      - id: black
        name: black (fix)
        entry: black
        language: system
        types: [python]
        require_serial: true

      - id: ruff
        name: ruff (fix)
        entry: ruff
        language: system
        types: [python]
        args: ["check", "--exit-non-zero-on-fix"]
        require_serial: true
