services:
  bot:
    image: schedule_bot
    container_name: bot
    restart: "no"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TOKEN: "$TOKEN"
      ADMIN_ID: "$ADMIN_ID"
      DB_URL: "$DB_URL"
      NATS_SERVERS: "$NATS_SERVERS"

      LOG_LEVEL: INFO
      LC_TIME: "ru_RU.UTF-8"
    volumes:
      - ./data/fonts:/root/.local/share/fonts
    depends_on:
      - db
      - nats
      - sender
      - renderer
      - converter

  sender:
    image: schedule_bot
    container_name: sender
    restart: "no"
    environment:
      TOKEN: "$TOKEN"
      NATS_SERVERS: "$NATS_SERVERS"
    entrypoint: ["python3", "-m", "services.sender"]
    depends_on:
      - nats

  renderer:
    image: schedule_bot
    container_name: renderer
    restart: "no"
    environment:
      DB_URL: "$DB_URL"
      NATS_SERVERS: "$NATS_SERVERS"
      LC_TIME: "ru_RU.UTF-8"
    entrypoint: ["python3", "-m", "services.renderer"]
    depends_on:
      - db
      - nats

  converter:
    image: schedule_bot
    container_name: converter
    restart: "no"
    environment:
      NATS_SERVERS: "$NATS_SERVERS"
    entrypoint: ["python3", "-m", "services.converter"]
    depends_on:
      - nats

  db:
    image: postgres:17.0-alpine
    container_name: db
    restart: "no"
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: "$POSTGRES_PASSWORD"
      POSTGRES_USER: "$POSTGRES_USER"
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: "no"
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "$PGADMIN_EMAIL"
      PGADMIN_DEFAULT_PASSWORD: "$PGADMIN_PASSWORD"
    volumes:
      - "./data/pgadmin:/var/lib/pgadmin"
    depends_on:
      - db

  nats:
    image: nats:latest
    container_name: nats
    restart: "no"
    entrypoint: /nats-server
    command: "-c /config/server.conf"
    volumes:
      - "./data/nats/data:/data"
      - "./data/nats/server.conf:/config/server.conf:ro"

  nats-nui:
    image: ghcr.io/nats-nui/nui:latest
    container_name: nats-nui
    restart: "no"
    ports:
      - "31311:31311"
    volumes:
      - "./data/nui/db:/db"
    depends_on:
      - nats
