services:
  bot:
    image: schedule_bot
    container_name: bot
    restart: "unless-stopped"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TOKEN: "$TOKEN"
      ADMIN_ID: "$ADMIN_ID"
      DB_URL: "$DB_URL"
      NATS_SERVERS: "nats://nats:4222"
      SOURCE_CODE_URL: "$SOURCE_CODE_URL"

      LOG_LEVEL: INFO
      LC_TIME: "ru_RU.UTF-8"
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "3"
    volumes:
      - ./data/fonts:/root/.local/share/fonts
    depends_on:
      - db
      - nats
      - sender
      - renderer
      - converter

  sender:
    image: schedule_bot
    container_name: sender
    restart: "unless-stopped"
    environment:
      TOKEN: "$TOKEN"
      NATS_SERVERS: "nats://nats:4222"
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "3"
    entrypoint: [".venv/bin/python3", "-m", "services.sender"]
    depends_on:
      - nats

  renderer:
    image: schedule_bot
    container_name: renderer
    restart: "unless-stopped"
    environment:
      DB_URL: "$DB_URL"
      NATS_SERVERS: "nats://nats:4222"
      LC_TIME: "ru_RU.UTF-8"
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "3"
    entrypoint: [".venv/bin/python3", "-m", "services.renderer"]
    depends_on:
      - db
      - nats

  converter:
    image: schedule_bot
    container_name: converter
    restart: "unless-stopped"
    environment:
      TOKEN: "$TOKEN"
      NATS_SERVERS: "nats://nats:4222"
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "3"
    entrypoint: [".venv/bin/python3", "-m", "services.converter"]
    depends_on:
      - nats

  db:
    attach: false
    image: postgres:17.0-alpine
    container_name: db
    restart: "unless-stopped"
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: "$POSTGRES_PASSWORD"
      POSTGRES_USER: "$POSTGRES_USER"
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "3"
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data

  dbeaver:
    attach: false
    image: dbeaver/cloudbeaver:24.3.3
    container_name: dbeaver
    restart: "unless-stopped"
    ports:
      - 8082:8978
    volumes:
      - "./data/dbeaver:/opt/cloudbeaver/workspace"
    depends_on:
      - db

  nats:
    attach: false
    image: nats:latest
    container_name: nats
    restart: "unless-stopped"
    entrypoint: /nats-server
    command: "-c /config/server.conf"
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "3"
    ports:
      - "127.0.0.1:4222:4222"
    volumes:
      - "./data/nats/data:/data"
      - "./data/nats/server.conf:/config/server.conf:ro"

  nats-nui:
    attach: false
    image: ghcr.io/nats-nui/nui:latest
    container_name: nats-nui
    restart: "unless-stopped"
    ports:
      - "31311:31311"
    volumes:
      - "./data/nui/db:/db"
    depends_on:
      - nats
