services:
  db:
    image: postgres:17.0-alpine
    container_name: db
    restart: "no"
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: "$POSTGRES_PASSWORD"
      POSTGRES_USER: "$POSTGRES_USER"
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: "no"
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "$PGADMIN_EMAIL"
      PGADMIN_DEFAULT_PASSWORD: "$PGADMIN_PASSWORD"
    volumes:
      - "./data/pgadmin:/var/lib/pgadmin"
    depends_on:
      - db

  nats:
    image: nats:latest
    container_name: nats
    restart: "no"
    entrypoint: /nats-server
    command: "-c /config/server.conf"
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - "./data/nats/data:/data"
      - "./data/nats/server.conf:/config/server.conf:ro"

  nats-nui:
    image: ghcr.io/nats-nui/nui:latest
    container_name: nats-nui
    restart: "no"
    ports:
      - "31311:31311"  # Порт для доступа к NATS NUI
    volumes:
      - "./data/nui/db:/db"
    depends_on:
      - nats
