services:
  db:
    image: postgres:17.0-alpine
    container_name: db
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: "$POSTGRES_PASSWORD"
      POSTGRES_USER: "$POSTGRES_USER"
    ports:
      - "5432:5432"
