"""Add display order as db field

Revision ID: 2eaac5b23896
Revises: 7e03d8f45d1a
Create Date: 2024-12-01 15:25:00.477899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2eaac5b23896'
down_revision: Union[str, None] = '7e03d8f45d1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('elements', sa.Column('display_order', sa.Integer(), nullable=True))

    op.execute(
        """
        WITH ordered AS (
            SELECT element_id, ROW_NUMBER() OVER (PARTITION BY user_id ORDER BY (SELECT NULL)) AS new_display_order
            FROM elements
        )
        UPDATE elements
        SET display_order = ordered.new_display_order - 1
        FROM ordered
        WHERE elements.element_id = ordered.element_id; 
        """
    )

    op.alter_column('elements', 'display_order',
               existing_type=sa.Integer(),
               nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('elements', 'display_order')
    # ### end Alembic commands ###
