"""Add cascade settings

Revision ID: 7e03d8f45d1a
Revises: 84198ee616fb
Create Date: 2024-12-01 13:31:20.847510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e03d8f45d1a'
down_revision: Union[str, None] = '84198ee616fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('elements_user_id_fkey', 'elements', type_='foreignkey')
    op.create_foreign_key(None, 'elements', 'users', ['user_id'], ['tg_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'elements', type_='foreignkey')  # type: ignore[arg-type]
    op.create_foreign_key('elements_user_id_fkey', 'elements', 'users', ['user_id'], ['tg_id'])
    # ### end Alembic commands ###
