"""Change max length for file id

Revision ID: 84198ee616fb
Revises: e30f9ff82539
Create Date: 2024-11-21 19:18:12.609448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84198ee616fb'
down_revision: Union[str, None] = 'e30f9ff82539'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('elements', 'file_id_photo',
               existing_type=sa.VARCHAR(length=83),
               type_=sa.VARCHAR(length=90),
               existing_nullable=True)
    op.alter_column('elements', 'file_id_document',
               existing_type=sa.VARCHAR(length=71),
               type_=sa.VARCHAR(length=90),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('elements', 'file_id_document',
               existing_type=sa.VARCHAR(length=90),
               type_=sa.VARCHAR(length=71),
               existing_nullable=True)
    op.alter_column('elements', 'file_id_photo',
               existing_type=sa.VARCHAR(length=90),
               type_=sa.VARCHAR(length=83),
               existing_nullable=True)
    # ### end Alembic commands ###
