"""Save templates as text in db

Revision ID: bcebcdbc8804
Revises: 2eaac5b23896
Create Date: 2024-12-31 17:57:52.095015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcebcdbc8804'
down_revision: Union[str, None] = '2eaac5b23896'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_template', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_template')
    # ### end Alembic commands ###
