"""Create table for user settings

Revision ID: dc541868ecb0
Revises: 91fead7b82ab
Create Date: 2025-06-15 12:31:20.964597

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dc541868ecb0"
down_revision: Union[str, None] = "91fead7b82ab"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "settings",
        sa.Column("tg_id", sa.BIGINT(), nullable=False),
        sa.Column("preferred_lang", sa.Enum("RUSSIAN", "ENGLISH", name="preferredlanguage"), nullable=True),
        sa.Column("accept_compressed", sa.Boolean(), server_default="false", nullable=False),
        sa.ForeignKeyConstraint(["tg_id"], ["users.tg_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("tg_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("settings")
    # ### end Alembic commands ###
