"""Reinit tables

Revision ID: e30f9ff82539
Revises:
Create Date: 2024-11-18 19:49:20.715019

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e30f9ff82539"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("tg_id", sa.BIGINT(), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("last_schedule", sa.TEXT(), nullable=True),
        sa.PrimaryKeyConstraint("tg_id"),
    )
    op.create_table(
        "elements",
        sa.Column("element_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.BIGINT(), nullable=True),
        sa.Column("name", sa.VARCHAR(length=50), nullable=False),
        sa.Column("file_id_photo", sa.VARCHAR(length=83), nullable=True),
        sa.Column("file_id_document", sa.VARCHAR(length=71), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.tg_id"],
        ),
        sa.PrimaryKeyConstraint("element_id"),
        sa.UniqueConstraint("user_id", "name", name="u_name_user"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("elements")
    op.drop_table("users")
    # ### end Alembic commands ###
